INSERT INTO public.sections (id, name, order_index, is_timed, time_limit_seconds, purpose) VALUES
  ('personality_wiring', 'Personality Wiring', 1, false, null, 'Big Five → MBTI-style type'),
  ('self_sabotage', 'Self-Sabotage Patterns', 2, false, null, 'Identify limiting behaviors'),
  ('optimal_environment', 'Optimal Work Environment', 3, false, null, 'Work/culture fit'),
  ('cognitive_architecture', 'Cognitive Architecture', 4, true, 540, 'IQ/processing estimate'),
  ('short_answer', 'Short Answer', 5, false, null, 'AI report personalization')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  order_index = EXCLUDED.order_index,
  is_timed = EXCLUDED.is_timed,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  purpose = EXCLUDED.purpose;

INSERT INTO public.questions (id, section_id, text, type, dimension, reverse_scored, weight, correct_answer, active) VALUES
  ('P1', 'personality_wiring', 'I am the life of the party.', 'likert', 'EI', false, 1.0, null, true),
  ('P2', 'personality_wiring', 'I don''t talk a lot.', 'likert', 'EI', true, 1.0, null, true),
  ('P3', 'personality_wiring', 'I feel comfortable around people.', 'likert', 'EI', false, 1.0, null, true),
  ('P4', 'personality_wiring', 'I keep in the background.', 'likert', 'EI', true, 1.0, null, true),
  ('P5', 'personality_wiring', 'I start conversations.', 'likert', 'EI', false, 1.0, null, true),  ('P6', 'personality_wiring', 'I have little to say.', 'likert', 'EI', true, 1.0, null, true),
  ('P7', 'personality_wiring', 'I talk to a lot of different people at parties.', 'likert', 'EI', false, 1.0, null, true),
  ('P8', 'personality_wiring', 'I am quiet around strangers.', 'likert', 'EI', true, 1.0, null, true),
  ('P9', 'personality_wiring', 'I have a rich vocabulary.', 'likert', 'SN', false, 1.0, null, true),
  ('P10', 'personality_wiring', 'I have difficulty understanding abstract ideas.', 'likert', 'SN', true, 1.0, null, true),
  ('P11', 'personality_wiring', 'I have a vivid imagination.', 'likert', 'SN', false, 1.0, null, true),
  ('P12', 'personality_wiring', 'I am not interested in abstract ideas.', 'likert', 'SN', true, 1.0, null, true),
  ('P13', 'personality_wiring', 'I have excellent ideas.', 'likert', 'SN', false, 1.0, null, true),
  ('P14', 'personality_wiring', 'I do not have a good imagination.', 'likert', 'SN', true, 1.0, null, true),
  ('P15', 'personality_wiring', 'I am quick to understand things.', 'likert', 'SN', false, 1.0, null, true),
  ('P16', 'personality_wiring', 'I spend time reflecting on things.', 'likert', 'SN', false, 1.0, null, true),
  ('P17', 'personality_wiring', 'I am interested in people.', 'likert', 'TF', false, 1.0, null, true),
  ('P18', 'personality_wiring', 'I feel little concern for others.', 'likert', 'TF', true, 1.0, null, true),
  ('P19', 'personality_wiring', 'I sympathize with others'' feelings.', 'likert', 'TF', false, 1.0, null, true),
  ('P20', 'personality_wiring', 'I insult people.', 'likert', 'TF', true, 1.0, null, true),
  ('P21', 'personality_wiring', 'I have a soft heart.', 'likert', 'TF', false, 1.0, null, true),
  ('P22', 'personality_wiring', 'I am not interested in other people''s problems.', 'likert', 'TF', true, 1.0, null, true),
  ('P23', 'personality_wiring', 'I take time out for others.', 'likert', 'TF', false, 1.0, null, true),
  ('P24', 'personality_wiring', 'I make people feel at ease.', 'likert', 'TF', false, 1.0, null, true),
  ('P25', 'personality_wiring', 'I am always prepared.', 'likert', 'JP', false, 1.0, null, true),
  ('P26', 'personality_wiring', 'I leave my belongings around.', 'likert', 'JP', true, 1.0, null, true),
  ('P27', 'personality_wiring', 'I pay attention to details.', 'likert', 'JP', false, 1.0, null, true),
  ('P28', 'personality_wiring', 'I make a mess of things.', 'likert', 'JP', true, 1.0, null, true),
  ('P29', 'personality_wiring', 'I get chores done right away.', 'likert', 'JP', false, 1.0, null, true),
  ('P30', 'personality_wiring', 'I often forget to put things back in their proper place.', 'likert', 'JP', true, 1.0, null, true),
  ('P31', 'personality_wiring', 'I like order.', 'likert', 'JP', false, 1.0, null, true),
  ('P32', 'personality_wiring', 'I shirk my duties.', 'likert', 'JP', true, 1.0, null, true),
  ('N1', 'personality_wiring', 'I get stressed out easily.', 'likert', 'NEURO', false, 1.0, null, true),
  ('N2', 'personality_wiring', 'I am relaxed most of the time.', 'likert', 'NEURO', true, 1.0, null, true),
  ('N3', 'personality_wiring', 'I worry about things.', 'likert', 'NEURO', false, 1.0, null, true),
  ('N4', 'personality_wiring', 'I seldom feel blue.', 'likert', 'NEURO', true, 1.0, null, true),
  ('N5', 'personality_wiring', 'I get upset easily.', 'likert', 'NEURO', false, 1.0, null, true),
  ('N6', 'personality_wiring', 'I change my mood a lot.', 'likert', 'NEURO', false, 1.0, null, true)
ON CONFLICT (id) DO UPDATE SET
  section_id = EXCLUDED.section_id,
  text = EXCLUDED.text,
  type = EXCLUDED.type,
  dimension = EXCLUDED.dimension,
  reverse_scored = EXCLUDED.reverse_scored,
  weight = EXCLUDED.weight,
  correct_answer = EXCLUDED.correct_answer,
  active = EXCLUDED.active;

INSERT INTO public.questions (id, section_id, text, type, dimension, reverse_scored, weight, correct_answer, active) VALUES
  ('S1', 'self_sabotage', 'I delay starting projects because I''m not sure I can do them perfectly.', 'likert', 'perfectionism', false, 1.0, null, true),
  ('S2', 'self_sabotage', 'I spend so much time planning that I don''t have enough time to execute.', 'likert', 'perfectionism', false, 1.0, null, true),
  ('S3', 'self_sabotage', 'I abandon projects when I realize they won''t meet my standards.', 'likert', 'perfectionism', false, 1.0, null, true),
  ('S4', 'self_sabotage', 'When I succeed, I attribute it more to luck or timing than my abilities.', 'likert', 'impostor', false, 1.0, null, true),
  ('S5', 'self_sabotage', 'I''m afraid people will discover I''m not as capable as they think.', 'likert', 'impostor', false, 1.0, null, true),
  ('S6', 'self_sabotage', 'I downplay my accomplishments when others praise me.', 'likert', 'impostor', false, 1.0, null, true),
  ('S7', 'self_sabotage', 'Before important tasks, I find reasons why I might not perform well.', 'likert', 'self_handicapping', false, 1.0, null, true),
  ('S8', 'self_sabotage', 'I put less effort into things that matter so I have an excuse if I fail.', 'likert', 'self_handicapping', false, 1.0, null, true),
  ('S9', 'self_sabotage', 'I take on too much so I can blame poor performance on being overcommitted.', 'likert', 'self_handicapping', false, 1.0, null, true),
  ('S10', 'self_sabotage', 'I check with others before making decisions I could make myself.', 'likert', 'validation_seeking', false, 1.0, null, true),
  ('S11', 'self_sabotage', 'Criticism from others affects my confidence more than it should.', 'likert', 'validation_seeking', false, 1.0, null, true),
  ('S12', 'self_sabotage', 'I avoid stating opinions until I know what others think.', 'likert', 'validation_seeking', false, 1.0, null, true),
  ('S13', 'self_sabotage', 'I stay in situations I''ve outgrown because change feels risky.', 'likert', 'avoidance', false, 1.0, null, true),
  ('S14', 'self_sabotage', 'I avoid difficult conversations even when they''re necessary.', 'likert', 'avoidance', false, 1.0, null, true),
  ('S15', 'self_sabotage', 'I''d rather keep the peace than advocate for what I want.', 'likert', 'avoidance', false, 1.0, null, true)
ON CONFLICT (id) DO UPDATE SET
  section_id = EXCLUDED.section_id,
  text = EXCLUDED.text,
  type = EXCLUDED.type,
  dimension = EXCLUDED.dimension,
  reverse_scored = EXCLUDED.reverse_scored,
  weight = EXCLUDED.weight,
  correct_answer = EXCLUDED.correct_answer,
  active = EXCLUDED.active;

INSERT INTO public.questions (id, section_id, text, type, dimension, reverse_scored, weight, correct_answer, active) VALUES
  ('E1', 'optimal_environment', 'I prefer work where I set my own priorities and methods.', 'likert', 'autonomy', false, 1.0, null, true),
  ('E2', 'optimal_environment', 'I work better with clear guidelines and defined processes.', 'likert', 'autonomy', false, 1.0, null, true),
  ('E3', 'optimal_environment', 'How much direction do you prefer from managers?', 'likert', 'autonomy', false, 1.0, null, true),
  ('E4', 'optimal_environment', 'I thrive in fast-paced environments with tight deadlines.', 'likert', 'pace', false, 1.0, null, true),
  ('E5', 'optimal_environment', 'I do my best work when I can take time to be thorough.', 'likert', 'pace', false, 1.0, null, true),
  ('E6', 'optimal_environment', 'I prefer working independently most of the time.', 'likert', 'social', false, 1.0, null, true),
  ('E7', 'optimal_environment', 'I feel energized by collaborating with a team throughout the day.', 'likert', 'social', false, 1.0, null, true),
  ('E8', 'optimal_environment', 'My ideal work involves:', 'likert', 'social', false, 1.0, null, true),
  ('E9', 'optimal_environment', 'I prefer stable positions over high-upside but uncertain opportunities.', 'likert', 'risk', false, 1.0, null, true),
  ('E10', 'optimal_environment', 'I''m willing to take a pay cut for work that''s more meaningful to me.', 'likert', 'risk', false, 1.0, null, true),
  ('E11', 'optimal_environment', 'I do my best work:', 'likert', 'work_mode', false, 1.0, null, true),
  ('E12', 'optimal_environment', 'I prefer environments that are:', 'likert', 'work_mode', false, 1.0, null, true)
ON CONFLICT (id) DO UPDATE SET
  section_id = EXCLUDED.section_id,
  text = EXCLUDED.text,
  type = EXCLUDED.type,
  dimension = EXCLUDED.dimension,
  reverse_scored = EXCLUDED.reverse_scored,
  weight = EXCLUDED.weight,
  correct_answer = EXCLUDED.correct_answer,
  active = EXCLUDED.active;

INSERT INTO public.questions (id, section_id, text, type, dimension, reverse_scored, weight, correct_answer, active) VALUES
  ('C1', 'cognitive_architecture', 'Cognitive item 1 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C2', 'cognitive_architecture', 'Cognitive item 2 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C3', 'cognitive_architecture', 'Cognitive item 3 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C4', 'cognitive_architecture', 'Cognitive item 4 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C5', 'cognitive_architecture', 'Cognitive item 5 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C6', 'cognitive_architecture', 'Cognitive item 6 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C7', 'cognitive_architecture', 'Cognitive item 7 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C8', 'cognitive_architecture', 'Cognitive item 8 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C9', 'cognitive_architecture', 'Cognitive item 9 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C10', 'cognitive_architecture', 'Cognitive item 10 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C11', 'cognitive_architecture', 'Cognitive item 11 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C12', 'cognitive_architecture', 'Cognitive item 12 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C13', 'cognitive_architecture', 'Cognitive item 13 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C14', 'cognitive_architecture', 'Cognitive item 14 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C15', 'cognitive_architecture', 'Cognitive item 15 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true),
  ('C16', 'cognitive_architecture', 'Cognitive item 16 (ICAR16 – update when available)', 'text', null, false, 1.0, null, true)
ON CONFLICT (id) DO UPDATE SET
  section_id = EXCLUDED.section_id,
  text = EXCLUDED.text,
  type = EXCLUDED.type,
  dimension = EXCLUDED.dimension,
  reverse_scored = EXCLUDED.reverse_scored,
  weight = EXCLUDED.weight,
  correct_answer = EXCLUDED.correct_answer,
  active = EXCLUDED.active;

INSERT INTO public.questions (id, section_id, text, type, dimension, reverse_scored, weight, correct_answer, active) VALUES
  ('O1', 'short_answer', 'What do you do for work, and what''s the hardest part of your job?', 'text', null, false, 1.0, null, true),
  ('O2', 'short_answer', 'If you knew you couldn''t fail, what would you do with your career?', 'text', null, false, 1.0, null, true),
  ('O3', 'short_answer', 'What do people misunderstand about you?', 'text', null, false, 1.0, null, true),
  ('O4', 'short_answer', 'What''s a goal you''ve had for over a year that you haven''t achieved? Why not?', 'text', null, false, 1.0, null, true),
  ('O5', 'short_answer', 'Describe a recent situation where you felt frustrated at work.', 'text', null, false, 1.0, null, true),
  ('O6', 'short_answer', 'When you imagine "making it," what does that look like?', 'text', null, false, 1.0, null, true),
  ('O7', 'short_answer', 'If you were a shape, what would you be and why?', 'text', null, false, 1.0, null, true),
  ('O8', 'short_answer', 'What do you fear people say about you behind your back?', 'text', null, false, 1.0, null, true),
  ('O9', 'short_answer', 'Describe yourself in three words. Now describe how others would describe you.', 'text', null, false, 1.0, null, true)
ON CONFLICT (id) DO UPDATE SET
  section_id = EXCLUDED.section_id,
  text = EXCLUDED.text,
  type = EXCLUDED.type,
  dimension = EXCLUDED.dimension,
  reverse_scored = EXCLUDED.reverse_scored,
  weight = EXCLUDED.weight,
  correct_answer = EXCLUDED.correct_answer,
  active = EXCLUDED.active;
