-- Seed for non-questionnaire data (e.g. users, etc.) can go here.
--
-- Questionnaire is the single source of truth in public.assessments (JSON column).
-- Structure: { free: [...], paid: [...] }
-- To bootstrap: ensure requirements/questionnaire.json exists, then run:
--   cd web && npm run questionnaire:load
-- To export from an existing assessments row: npm run questionnaire:export
