-- Questionnaire definitions as JSON (one row per quiz version), matching requirements doc structure.
-- Version is a UUID or semantic version identifier for the quiz.

CREATE TABLE IF NOT EXISTS public.questionnaire_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  questionnaire jsonb NOT NULL,
  version varchar(36) NOT NULL,
  language_key varchar(5) NOT NULL DEFAULT 'en',
  CONSTRAINT questionnaire_versions_version_key UNIQUE (version)
);

COMMENT ON TABLE public.questionnaire_versions IS 'One row per questionnaire/quiz version; questionnaire stored as JSON for flexibility.';
COMMENT ON COLUMN public.questionnaire_versions.version IS 'UUID or semantic version (e.g. v1.0) for this quiz.';
COMMENT ON COLUMN public.questionnaire_versions.questionnaire IS 'JSON array of sections, each with id, name, order_index, is_timed, time_limit_seconds, purpose, questions[].';

-- Build initial questionnaire from existing sections + questions (if they exist)
INSERT INTO public.questionnaire_versions (questionnaire, version, language_key)
SELECT COALESCE((
  SELECT jsonb_agg(
    jsonb_build_object(
      'id', s.id,
      'name', s.name,
      'order_index', s.order_index,
      'is_timed', COALESCE(s.is_timed, false),
      'time_limit_seconds', s.time_limit_seconds,
      'purpose', s.purpose,
      'questions', (
        SELECT jsonb_agg(
          jsonb_build_object(
            'id', q.id,
            'text', q.text,
            'type', q.type,
            'dimension', q.dimension,
            'reverse_scored', COALESCE(q.reverse_scored, false),
            'weight', COALESCE(q.weight, 1),
            'correct_answer', q.correct_answer,
            'active', COALESCE(q.active, true)
          ) ORDER BY q.id
        )
        FROM public.questions q
        WHERE q.section_id = s.id
      )
    ) ORDER BY s.order_index
  )
  FROM public.sections s
), '[]'::jsonb),
'v1.0',
'en'
WHERE EXISTS (SELECT 1 FROM public.sections LIMIT 1)
  AND NOT EXISTS (SELECT 1 FROM public.questionnaire_versions WHERE version = 'v1.0');

-- If no sections exist yet (fresh DB), insert a minimal placeholder so the table is usable
INSERT INTO public.questionnaire_versions (questionnaire, version, language_key)
SELECT '[]'::jsonb, 'v1.0', 'en'
WHERE NOT EXISTS (SELECT 1 FROM public.questionnaire_versions WHERE version = 'v1.0');

-- Link assessment attempts to questionnaire version
ALTER TABLE public.assessments
  ADD COLUMN IF NOT EXISTS questionnaire_version_id bigint REFERENCES public.questionnaire_versions(id);

-- Backfill existing assessments to use v1.0
UPDATE public.assessments a
SET questionnaire_version_id = (SELECT id FROM public.questionnaire_versions WHERE version = 'v1.0' LIMIT 1)
WHERE a.questionnaire_version_id IS NULL
  AND EXISTS (SELECT 1 FROM public.questionnaire_versions WHERE version = 'v1.0');

-- Index for lookups by version
CREATE INDEX IF NOT EXISTS idx_questionnaire_versions_version ON public.questionnaire_versions (version);

-- RLS: allow anon to read questionnaire versions (needed when start/resume serve questionnaire)
ALTER TABLE public.questionnaire_versions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_select_questionnaire_versions" ON public.questionnaire_versions
  FOR SELECT TO anon USING (true);
